spring.application.name=Backend2FakeStoreApp

spring.datasource.url=jdbc:postgresql://localhost:5234/FakeStoreDB
spring.datasource.username=fakestore_admin
spring.datasource.password=fakestore_password
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
server.port=8080

# FakeStore för WebClientConfig
app.fakestore.fakeStoreUrl=https://fakestoreapi.com

# Spring Security
spring.security.user.name=admin
spring.security.user.password=password