spring.application.name=Backend2FakeStoreApp

spring.datasource.url=jdbc:postgresql://localhost:5432/FakeStoreDB
spring.datasource.username=fakestore_admin
spring.datasource.password=fakestore_password
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
server.port=8080